algoritmo "UmaPartidaDeFutebol"
var
   bangu, madureira, dif: inteiro
inicio
      Escreval("   BANGU x MADUREIRA")
      Escreval("-----------------------")
      Escreva("Quantos gols do BANGU? ")
      Leia(bangu)
      Escreva("Quantos gols do MADUREIRA? ")
      Leia(madureira)
      Escreval("-----------------------")
      dif <- abs(bangu - madureira)
      Escreval("DIFERENCA: ", dif)
      Escreval("STATUS: ")
fimalgoritmo
