Algoritmo "media_ponderada"


Var
   n, i: inteiro
   valor1, valor2, valor3, media: real

Inicio
      Escreva("Quantos casos voce vai digitar? ")
      leia(n)
      Escreval("Digite tres numeros: ")
      para i de 1 ate n faca
      leia(valor1)
      leia(valor2)
      leia(valor3)
      media <- (valor1 * 2 + valor2 * 3 + valor3 * 5)/10
      Escreval("MEDIA = ", media:1:1)
      Escreval("Digite tres numeros: ")
      
       fimpara




Fimalgoritmo